#VoteMod - https://github.com/JCox06/VoteMod
#This plugin requires vault to be installed to the server
#This plugin requires online mode to be set to true
#It is strongly recommended installing a permission plugin that can handle offline player calls (like LuckPerms)
#Without the above criteria this software will NOT RUN as expected and WILL crash


#Language - Default will choose the language of the JVM installed
#Supported Languages
#en, en, de
lang: default

#Number of votes ongoing allowed at one time. It is recommended to have this on 1
allowed-ongoing-votes: 1

#Give bypass to players who have recently had a vote denied.
vote-resistance: true
#How long should a player have resistance, in minutes
vote-resistance-expire: 5

#Number of votes required for a vote to be classed as successful
# % will take the value and find the % of the amount of players to class when a vote is complete
# - will take the value and subtract from the number of online players
# a standard value will hard code the number of players needed for a successful vote
needed-votes: 1-

#How many players need to be online before someone can vote.
required-players: 5


#How long does it take for a ban to expire (in hours). Set 0 for never
ban-time: 0

#Votes timeout in seconds. How long does it take for a vote to expire
timeout: 60

#Logs additional messages in the console. Useful for finding and reporting bugs
debug-mode: false

