#VoteMod - https://github.com/JCox06/VoteMod
#It is highly recommended installing a permission plugin and Vault to this server.
#If you do not have a permission plugin installed, then Vault will be unable to make
#offline player calls, the functionality of the plugin will be restricted without these
#critical plugins installed.


#Language - Default will choose the language of the JVM installed
#Supported Languages
#en, en, de
lang: default

#Number of votes ongoing allowed at one time. It is recommended to have this on 1
allowed-ongoing-votes: 1

#Give bypass to players who have recently had a vote denied.
vote-resistance: true
#How long should a player have resistance, in minutes
vote-resistance-expire: 5

#Number of votes required for a full vote completion. This is expressed as a percentage
needed-votes: 50

#How many players need to be online before someone can vote.
required-players: 5

#IP or standard Ban
ban-method: standard

#How long does it take for a ban to expire (in hours). Set 0 for never
ban-time: 0

#Votes timeout in seconds. How long does it take for a vote to expire
timeout: 60

#Logs additional messages in the console. Useful for debugging errors.
debug-mode: false

