#  MIT License
#
#    Copyright (c) 2021 Jacob Cox
#
#    Permission is hereby granted, free of charge, to any person obtaining a copy
#    of this software and associated documentation files (the "Software"), to deal
#    in the Software without restriction, including without limitation the rights
#    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#    copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#    The above copyright notice and this permission notice shall be included in all
#    copies or substantial portions of the Software.
#
#    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#    SOFTWARE.

name: VoteMod
main: uk.co.jcox.votemod.Main
version: ${project.version}
author: Jacob Cox
api-version: 1.17

depend: [Vault]

#permissions:
#  votemod.vote:
#    description: Allows players to start votes and vote on ongoing votes
#  votemod.cancel:
#    description: Cancels votes
#  votemod.list:
#    description: See a list of votes
#  votemod.clear:
#    description: Clear all votes
#  votemod.bypass:
#    description: When assigned it stops a particular player from being voted


permissions:
  VoteMod.*:
    default: op
    description: Gives access to everything in VoteMod including the managing of votes
    children:
      VoteMod.participate: true
      VoteMod.start: true
      VoteMod.manage: true

  VoteMod.standard:
    description: Gives access to standard features such as creating and participating in votes
    children:
      VoteMod.participate: true
      VoteMod.start: true

  VoteMod.manage:
    description: Gives access to destroying votes
    children:
      VoteMod.clear: true
      VoteMod.delete: true

  VoteMod.start:
    description: Gives access to starting votes of any type
    children:
      VoteMod.startban: true
      VoteMod.startpardon: true

  VoteMod.participate:
    description: Gives access to allow voting of already existing votes
    VoteMod.ban: true
    VoteMod.startpardon: true


  #Actual Permissions
  VoteMod.clear:
    description: Gives access to deleting all votes
  VoteMod.delete:
    description: Gives access to removing specific votes
  VoteMod.startban:
    description: Gives access to starting a vote ban
  VoteMod.startpardon:
    description: Gives access to starting a vote pardon
  VoteMod.ban:
    description: Gives access to participating in a vote ban
  VoteMod.pardon:
    description: Gives access to participating in a vote pardon
  VoteMod.bypass:
    description: Players with this permission cannot be voted.
    default: op
